# ===============================
# CONFIGURACIÓN GENERAL
# ===============================
spring.application.name=agrogreen-backend
server.port=8080

# ===============================
# CONFIGURACIÓN POSTGRESQL
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5434/agrogreen_db
spring.datasource.username=postgres
spring.datasource.password=Artunduaga_316
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# CONFIGURACIÓN JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# CONFIGURACIÓN FLYWAY
# ===============================
spring.flyway.enabled=false
spring.jpa.open-in-view=false

# JWT Configuration
app.jwt.secret=${JWT_SECRET:AgroGreenSmartSystemSecretKeyForDevelopmentOnly123456789}
app.jwt.expiration-ms=86400000

app.google.client-id=519711057417-b9ou5d8259dp75hipu8djrd524hsrms0.apps.googleusercontent.com